project:
  type: website
  output-dir: docs

website:
  title: "dygraphs"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog


format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "42dot Sans"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto
