project:
  type: website
  output-dir: docs

website:
  title: "dygraphs"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog


format:
  html:
    theme:
      light: litera
      dark: darkly
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap
    include-before-body: script.js


execute:
  freeze: auto
