project:
  type: website
  output-dir: docs

website:
  title: "dygraphs"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: index.qmd#grp-info
        text: Group Information
      - href: index.qmd#intro
        text: Introduction
      - href: index.qmd#inst-and-setup
        text: Installation and Setup
      - href: index.qmd#key-features
        text: Key Features and Explanation
      - href: index.qmd#use-cases
        text: Use Cases
      - href: index.qmd#conc
        text: Conclusion
      - href: index.qmd#ref
        text: References


format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto
